import type { WorkflowNodeModelCapability, WorkflowNodeStage, WorkflowNodeType } from '../../shared/src/workflow/node-contracts';

export interface User {
  isLoggedIn: boolean;
  email: string;
  role: 'ADMIN' | 'DEVELOPER' | 'USER';
}

export interface PipelineStep {
  id: string; // "01" to "12"
  name: string;
  description: string;
  status: 'pending' | 'active' | 'completed';
  workDetail?: string; // markdown content generated by AI or pre-loaded
}

export interface Project {
  id: string;
  name: string;
  type: string;
  currentStepId: string; // ID of current step e.g. "05"
  steps: Record<string, string>; // Maps step ID to its generated markdown data
}

export interface IndustryNews {
  id: string;
  title: string;
  category: string;
  date: string;
  summary: string;
}


// --- NEW TYPES FROM REPOSITORY ---

export interface CanvasNode {
  id: string;
  name: string;
  type: WorkflowNodeType | (string & {}); // Keep legacy canvas node strings readable.
  x: number;
  y: number;
  parentId?: string | null;
  collapsed?: boolean;
  status?: string; // '审核中' | '定稿' | '草稿'
  prompt?: string;
  refImage?: string;
  moduleType?: '04' | '05';
  
  // Image & Video Generator additions
  model?: string;
  custom_url?: string;
  custom_key?: string;
  custom_model?: string;
  use_custom_api?: boolean;
  custom_config_id?: string;
  selected_api_id?: string;
  generated_media?: string;
  generated_media_asset_id?: string;
  isLoading?: boolean;
  progress?: number; // 0 to 100
  statusMessage?: string;
  workflow_task_id?: string;
  workflow_run_id?: string;
  error?: string;
  assistant_auto_run_requested_at?: string;
  assistant_auto_run_action_id?: string;

  // Rich AI Image node configurations (libtv features)
  aspect_ratio?: string;
  width?: number;
  height?: number;
  resolution?: string;
  image_quality?: 'low' | 'medium' | 'standard' | 'high' | 'auto';
  output_format?: 'png' | 'jpeg' | 'webp';
  output_compression?: number;
  image_background?: 'auto' | 'opaque' | 'transparent';
  moderation?: 'auto' | 'low';
  partial_images?: number;
  stream?: boolean;
  num_outputs?: number;
  style_preset?: string;
  negative_prompt?: string;
  cfg_scale?: number;
  steps?: number;
  seed?: number;

  // Video Generator specific configurations
  video_resolution?: string;
  video_duration?: number;
  generate_audio?: boolean;
  show_advanced?: boolean;
  uploaded_images?: string[];
  original_uploaded_images?: string[];
  original_generated_media?: string;
  video_generation_mode?: 'text_to_video' | 'image_to_video' | 'first_last_frame' | 'reference_to_video' | 'video_edit' | 'all_in_one_reference' | 'needs_user_choice';
  video_media_list?: { url: string; assetId?: string; type: 'image' | 'video' | 'audio'; name: string; duration?: string; }[];
  imageGenerationMode?: 'auto' | 'text_to_image' | 'image_to_image' | 'image_edit';
  imageInputs?: {
    referenceImageAssetIds?: string[];
    sourceImageAssetId?: string;
    maskImageAssetId?: string;
    editInstruction?: string;
  };
  videoGenerationMode?: 'auto' | 'text_to_video' | 'image_to_video' | 'first_last_frame' | 'reference_to_video' | 'video_edit';
  videoInputs?: {
    firstFrameAssetId?: string;
    lastFrameAssetId?: string;
    referenceImageAssetIds?: string[];
    sourceVideoAssetId?: string;
    referenceVideoAssetId?: string;
    audioAssetId?: string;
    editInstruction?: string;
  };

  // Scene3D Director Stage v1
  scene3dState?: Record<string, any>;
  scene3dCaptures?: Record<string, any>[];
  activeCameraId?: string;
  scene3dLastCaptureUrl?: string;
  scene3dLastCaptureAssetId?: string;
  scene3dMotionPrompt?: string;
  scene3dMoodPrompt?: string;
  scene3dRenderStylePrompt?: string;
  scene3dVisualContext?: Record<string, any>;
}

export interface ChatMessage {
  id: string;
  sender: 'ai' | 'user';
  text: string;
  timestamp: string;
}

export interface PromptShot {
  id: string;
  shotNumber: string;
  duration: string;
  shotType: string;
  cameraMotion: string;
  visualPrompt: string;
  motionPrompt: string;
  remarks: string;
  audioKey?: string;
}

export interface ReferenceFile {
  id: string;
  name: string;
  category: 'story' | 'art' | 'music' | 'video';
  mimeType?: string;
  size?: string;
  url?: string;
}

export interface VideoClip {
  id: string;
  name: string;
  duration: string;
  thumbnail: string;
  active?: boolean;
}

export type EditingTrackType = 'VIDEO' | 'AUDIO' | 'TEXT';
export type EditingClipKind = 'VIDEO' | 'IMAGE' | 'AUDIO' | 'TEXT';

export interface EditingClip {
  id: string;
  assetId?: string;
  kind: EditingClipKind;
  name?: string;
  text?: string;
  startMs: number;
  durationMs: number;
  sourceInMs: number;
  sourceOutMs: number;
  volume: number;
  muted: boolean;
  fadeInMs: number;
  fadeOutMs: number;
}

export interface EditingTrack {
  id: string;
  type: EditingTrackType;
  name: string;
  clips: EditingClip[];
}

export interface EditingTimelineMarker {
  id: string;
  atMs: number;
  label: string;
  color?: string;
}

export interface EditingTimelineTransition {
  id: string;
  atMs: number;
  type: string;
  durationMs?: number;
  fromClipId?: string;
  toClipId?: string;
}

export interface EditingTimelineEffect {
  id: string;
  atMs: number;
  type: string;
  targetClipId?: string;
  durationMs?: number;
  note?: string;
}

export interface EditingTimeline {
  version: 1;
  durationMs: number;
  settings: {
    fps: number;
    width: number;
    height: number;
    aspectRatio: string;
  };
  tracks: EditingTrack[];
  metadata?: {
    importedAssets?: EditingAsset[];
    markers?: EditingTimelineMarker[];
    transitions?: EditingTimelineTransition[];
    effects?: EditingTimelineEffect[];
  };
}

export interface EditingProject {
  id: string;
  ownerId: string;
  title: string;
  schemaVersion: number;
  durationMs: number;
  timelineJson: EditingTimeline;
  metadata?: Record<string, any> | null;
  createdAt: string;
  updatedAt: string;
}

export interface EditingAsset {
  id: string;
  title: string;
  type: 'VIDEO' | 'IMAGE' | 'AUDIO';
  kind: EditingClipKind;
  mimeType?: string | null;
  sizeBytes?: number | null;
  url: string;
  createdAt: string;
}

export type ProductionStage = WorkflowNodeStage;

export type PromptOptimizationProfileKey = 'video_prompt' | 'image_prompt' | 'reverse_prompt' | 'image_edit_prompt' | 'music_prompt';

export interface PromptOptimizationProfile {
  id: string;
  key: PromptOptimizationProfileKey;
  label: string;
  description?: string | null;
  systemPrompt: string;
  defaultSystemPrompt: string;
  isEnabled: boolean;
  sortOrder: number;
  updatedById?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export type PipelineAssistantActionType =
  | 'SCRIPT_CREATE_OR_UPDATE'
  | 'SCRIPT_IMPORT_PARSE'
  | 'DIRECTOR_PROMPT_FILL'
  | 'DIRECTOR_PROMPT_GENERATE'
  | 'ART_NODE_CREATE'
  | 'ART_NODE_UPDATE'
  | 'ART_GENERATE_START'
  | 'SHOT_NODE_CREATE'
  | 'SHOT_NODE_UPDATE'
  | 'SHOT_GENERATE_START'
  | 'EDIT_TIMELINE_UPDATE'
  | 'EDIT_ROUGH_CUT_CREATE'
  | 'EDIT_EFFECT_OR_AUDIO_MARKER_ADD';

export type PipelineAssistantActionStatus = 'PENDING' | 'CONFIRMED' | 'REJECTED' | 'EXPIRED' | 'FAILED';

export interface PipelineAssistantAction {
  id: string;
  type: PipelineAssistantActionType;
  stage: ProductionStage;
  status: PipelineAssistantActionStatus;
  targetId?: string | null;
  payload?: Record<string, any>;
  previewText: string;
  expiresAt?: string;
  createdAt?: string;
  executionResult?: Record<string, any>;
  errorMessage?: string;
}

export interface PipelineAssistantMessage extends ChatMessage {
  actions?: PipelineAssistantAction[];
}

export interface TeamProject {
  id: string;
  name: string;
  description?: string;
  createdById?: string | null;
  projectKind?: 'PERSONAL' | 'TEAM';
  workflowType?: string | null;
  memberCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface TeamProjectMember {
  id: string;
  projectId: string;
  userId: string;
  role: 'OWNER' | 'MEMBER';
  projectRole?: 'PROJECT_DEVELOPER' | null;
  teamRole?: 'TEAM_LEADER' | null;
  projectDeveloperExpiresAt?: string | null;
  teamLeaderExpiresAt?: string | null;
  user?: BasicUserProfile & {
    role?: 'ADMIN' | 'DEVELOPER' | 'USER';
    status?: 'ACTIVE' | 'DISABLED';
  };
  createdAt?: string;
}

export interface TeamMemberCandidate {
  id: string;
  email?: string | null;
  username?: string | null;
  displayName?: string | null;
  role?: 'ADMIN' | 'DEVELOPER' | 'USER';
  status?: 'ACTIVE' | 'DISABLED';
}

export interface SlashProductionAsset {
  id: string;
  projectId: string | null;
  projectName?: string | null;
  deletedProjectId?: string | null;
  deletedProjectName?: string | null;
  stage: ProductionStage;
  scope: string;
  reviewStatus: string;
  originalName: string;
  displayName: string;
  description?: string;
  mimeType?: string | null;
  sizeBytes?: number | null;
  currentSnapshotId?: string | null;
  streamUrl?: string | null;
  createdAt?: string;
  updatedAt?: string;
  archivedAt?: string | null;
  deletedAt?: string | null;
}

export interface ProductionAsset {
  id: string;
  projectId: string | null;
  projectName?: string | null;
  stage: ProductionStage;
  scope: 'PERSONAL' | 'TEAM' | 'INTERNAL';
  reviewStatus: 'UNREVIEWED' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'ARCHIVED' | 'REFERENCE';
  originalName: string;
  displayName: string;
  description?: string;
  mimeType?: string | null;
  sizeBytes?: number | null;
  version: number;
  currentSnapshotId?: string | null;
  sourceType?: string | null;
  sourceId?: string | null;
  streamUrl?: string | null;
  creator?: BasicUserProfile | null;
  submitter?: BasicUserProfile | null;
  reviewer?: BasicUserProfile | null;
  createdAt?: string;
  updatedAt?: string;
  archivedAt?: string | null;
  deletedAt?: string | null;
}

export interface BasicUserProfile {
  id: string;
  displayName?: string | null;
  email?: string | null;
  username?: string | null;
}

export type NotificationCategory = 'NOTICE' | 'BROADCAST' | 'ANNOUNCEMENT';

export interface AppNotificationAttachment {
  id: string;
  mediaAssetId: string;
  displayName: string;
  mimeType?: string | null;
  sizeBytes?: number | null;
  previewUrl: string;
  downloadUrl: string;
  createdAt?: string;
}

export interface AppNotification {
  id: string;
  type: string;
  category: NotificationCategory;
  categoryLabel: string;
  audience: 'USER' | 'PROJECT' | 'GLOBAL';
  title: string;
  content: string;
  targetType: string;
  targetId?: string | null;
  projectId?: string | null;
  projectName?: string | null;
  sender?: BasicUserProfile | null;
  metadata?: Record<string, any> | null;
  readAt?: string | null;
  deletedAt?: string | null;
  expiresAt?: string | null;
  createdAt: string;
  attachments: AppNotificationAttachment[];
}

export interface ProductionAssetSnapshot {
  id: string;
  assetId: string;
  version: number;
  reviewStatus: ProductionAsset['reviewStatus'];
  originalName: string;
  displayName: string;
  mimeType?: string | null;
  sizeBytes?: number | null;
  reviewNote?: string | null;
  payloadPreview?: string;
  streamUrl?: string | null;
  asset?: ProductionAsset | null;
  createdBy?: BasicUserProfile | null;
  reviewedBy?: BasicUserProfile | null;
  createdAt?: string;
  reviewedAt?: string | null;
}

export interface InternalAssetItem {
  kind: 'snapshot' | 'reference';
  id: string;
  projectId: string | null;
  stage: ProductionStage | null;
  reviewStatus: ProductionAsset['reviewStatus'];
  displayName: string;
  originalName: string;
  mimeType?: string | null;
  sizeBytes?: number | null;
  snapshot?: ProductionAssetSnapshot | null;
  asset?: ProductionAsset | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface SlashAssetResolveResult {
  fromStage: ProductionStage;
  sourceStage: ProductionStage;
  insertMode: 'TEXT_CONTENT' | 'ATTACHMENT_REFERENCE' | 'IMPORT_TO_EDIT_BIN';
  asset: SlashProductionAsset;
  snapshot?: { id: string; assetId: string; version: number } | null;
  content?: string;
  reference?: {
    assetId: string;
    snapshotId?: string | null;
    mediaAssetId?: string | null;
    rowNumber?: number;
    field?: string;
    streamUrl?: string | null;
  };
}

export interface CustomApiConfig {
  id: string;
  customModelId?: string;
  alias: string;
  displayName?: string;
  provider?: string;
  type: 'image' | 'video' | 'text';
  capability?: Extract<WorkflowNodeModelCapability, 'TEXT_GENERATOR' | 'IMAGE_GENERATOR' | 'VIDEO_GENERATOR'>;
  canonicalModelId?: string;
  activeCapabilityRevisionId?: string;
  capabilityProfile?: ModelCapabilityProfile;
  baseUrl: string;
  apiKey?: string;
  hasApiKey?: boolean;
  keyPreview?: string;
  modelName: string;
  isEnabled?: boolean;
  supportsAspectRatio?: boolean;
  supportsResolution?: boolean;
  supportsQuality?: boolean;
  supportsNegativePrompt?: boolean;
  supportsNumOutputs?: boolean;
  autoDetectParams?: boolean;
  metadata?: {
    resolutions?: string[];
    ratios?: string[];
    qualities?: string[];
    description?: string;
  };
}

export interface ModelCapabilityRevision {
  id: string;
  revision: number;
  params?: any;
  sourceHash?: string | null;
  changedSummary?: string | null;
  createdAt?: string;
}

export interface ModelCapabilityProfile {
  id: string;
  canonicalModelId: string;
  officialModelId?: string | null;
  provider: string;
  capability: Extract<WorkflowNodeModelCapability, 'TEXT_GENERATOR' | 'IMAGE_GENERATOR' | 'VIDEO_GENERATOR'>;
  aliases?: string[];
  sourceUrls?: string[];
  verificationStatus: 'VERIFIED' | 'UNVERIFIED' | 'MANUAL_VERIFIED' | 'DEPRECATED';
  executable: boolean;
  activeRevisionId?: string | null;
  activeRevision?: ModelCapabilityRevision | null;
  imageCapabilities?: any;
  videoCapabilities?: any;
  textCapabilities?: any;
  runtime?: {
    endpoint?: string;
    streamEndpoint?: string;
    responsePaths?: string[];
    streamChunkPaths?: string[];
    taskIdPaths?: string[];
    pollEndpoint?: string;
    pollResultPaths?: string[];
    pollStatusPaths?: string[];
    failedStatuses?: string[];
  };
  lastCheckedAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface OfficialCapabilityJsonProbe {
  canonicalModelId: string;
  officialModelId?: string | null;
  provider: string;
  capability: Extract<WorkflowNodeModelCapability, 'TEXT_GENERATOR' | 'IMAGE_GENERATOR' | 'VIDEO_GENERATOR'>;
  verificationStatus: 'VERIFIED' | 'UNVERIFIED' | 'MANUAL_VERIFIED' | 'DEPRECATED';
  sourceUrls: string[];
  sourceHash: string;
}

export interface OfficialCapabilityUrlProbe {
  url: string;
  host: string;
  title: string;
  contentType: string;
  bytesScanned: number;
  matchedCanonicalModel: boolean;
  candidate: {
    canonicalModelId?: string | null;
    capability?: 'TEXT_GENERATOR' | 'IMAGE_GENERATOR' | 'VIDEO_GENERATOR' | null;
    modelHints: string[];
    sizeHints: string[];
    ratioHints: string[];
    qualityHints: string[];
    durationHints: number[];
  };
  structuredCandidate?: any | null;
  verificationStatus: 'UNVERIFIED';
  executable: false;
  note: string;
}

export interface HistoryItem {
  id: string;
  timestamp: Date;
  featureMode: string;
  input: string;
  output: string;
  attachments: { name: string; mimeType: string; data: string }[];
  model: string;
  mode?: string;
  duration?: string;
  techniques?: string[];
  styles?: string[];
  promptCount?: number;
  customModelId?: string;
  customModelAlias?: string;
  projectId?: string;
  projectTitle?: string;
  outputType?: string;
  source?: string;
  metadata?: Record<string, any>;
}

export interface SavedPrompt {
  id: string;
  title: string;
  content: string;
  timestamp: Date;
}

export interface CanvasState {
  nodes: CanvasNode[];
  shotNodes: CanvasNode[];
  shots: PromptShot[];
  apiConfigs: CustomApiConfig[];
  activeStage?: string;
  metadata?: Record<string, any>;
}
